create table Album (id bigint generated by default as identity, cover varchar(255), name varchar(100) not null, artist_id bigint, primary key (id))
create table Artist (id bigint generated by default as identity, name varchar(100) not null, primary key (id))
create table Genre (id bigint generated by default as identity, description varchar(250) not null, name varchar(100) not null, primary key (id))
create table Playlist (id bigint generated by default as identity, artwork varchar(1000) not null, description varchar(500) not null, name varchar(100) not null, primary key (id))
create table Track (id bigint generated by default as identity, duration integer not null, lyrics varchar(255), name varchar(100) not null, album_id bigint, genre_id bigint, playlist_id bigint, primary key (id))
create table User (id bigint generated by default as identity, password varchar(255), username varchar(255), primary key (id))
alter table Album add constraint UK_ee9y9ts3adxakpjrllvhh6qh3 unique (name)
alter table Artist add constraint UK_qk616bidu9lfr95vukvwwfawq unique (name)
alter table Genre add constraint UK_ga4mxmqaho3u9vvin1cr4ubja unique (description)
alter table Genre add constraint UK_f0cxck09qxl9ea0dhvl6aejis unique (name)
alter table Playlist add constraint UK_do5cg22wp7lu6317murgku239 unique (name)
alter table Track add constraint UK_fl2autu81ivlacmikut36invq unique (name)
alter table User add constraint UK_jreodf78a7pl5qidfh43axdfb unique (username)
alter table Album add constraint FKeornxb63o72l560qifpvd6ty foreign key (artist_id) references Artist
alter table Track add constraint FKbvgarccx945r5j9owhpoyh2hx foreign key (album_id) references Album
alter table Track add constraint FKd6jhw9lm3t4glfpi2nkttu6k1 foreign key (genre_id) references Genre
alter table Track add constraint FK2omxdingg3h138ilrtcry2pjn foreign key (playlist_id) references Playlist
