create table album (
	id bigint generated by default as identity,
	cover varchar(255),
	name varchar(100) not null unique,
	artist_id bigint, primary key (id),
	foreign key (artist_id) references artist
)

create table artist (
	id bigint generated by default as identity,
	name varchar(100) not null unique,
	primary key (id)
)
	
create table genre (
	id bigint generated by default as identity,
	description varchar(250) not null unique,
	name varchar(100) not null unique,
	primary key (id)
)

create table playlist (
	id bigint generated by default as identity,
	artwork varchar(1000) not null,
	description varchar(500) not null,
	name varchar(100) not null unique,
	primary key (id)
)

create table track (
	id bigint generated by default as identity,
	duration integer not null, lyrics varchar(255),
	name varchar(100) not null unique, 
	album_id bigint,
	genre_id bigint,
	playlist_id bigint,
	primary key (id),
	foreign key (album_id) references album,
	foreign key (genre_id) references genre,
	foreign key (playlist_id) references playlist
);